name: Tests Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
    inputs:
      deploy_to:
        description: 'Deploy to which system (stg|prod)'
        required: true
        default: stg
env:
  DEPLOY_TO: ${{ github.event.inputs.deploy_to }}

jobs:

  app-tests:
    name: Tests
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2

      - name: Echo env
        env:
          STEP_DEPLOY_TO: ${{ github.event.inputs.deploy_to }}
        run: |
          echo DEPLOY_TO        = $DEPLOY_TO
          echo STEP_DEPLOY_TO   = $STEP_DEPLOY_TO
          echo e.STEP_DEPLOY_TO = ${{ env.STEP_DEPLOY_TO }}
          echo env.DEPLOY_TO    = ${{ env.DEPLOY_TO }}
          echo github object    = ${{ github }}
          echo github object*   = ${{ github.* }}

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Generate Key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
        run: vendor/bin/phpunit

#      - name: Trigger build workflow
#        if: success()
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GH_REPO_PAT }}
#          event-type: build-assets
#          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

